#!/usr/bin/env python3
"""
Enhanced FanDuel Submission Creator

Automatically converts enhanced lineups to FanDuel submission format
and populates the actual FanDuel CSV template.
"""


import pandas as pd
import glob
import os
from datetime import datetime

def get_valid_player_ids():
    slate_path = '../fd_current_slate/fd_slate_today.csv'
    if not os.path.exists(slate_path):
        print(f"❌ Slate file not found: {slate_path}")
        return set()
    slate_df = pd.read_csv(slate_path)
    # Filter out players where Played == 0
    valid = slate_df[slate_df['Played'] > 0]
    # Filter out players where the batting order column is 0, '0', 'O', or 'o'
    eligibility_col = slate_df.columns[-2]
    valid = valid[~valid[eligibility_col].astype(str).isin(['0', 'O', 'o'])]
    valid = valid[valid[eligibility_col] != 0]
    valid_ids = set(valid['Id'].astype(str))
    return valid_ids

def load_enhanced_lineups():
    """Load all enhanced lineups generated by the optimizer"""
    lineup_files = glob.glob("../data/enhanced_lineup_*.csv")
    # Also check for slate_lineups.csv
    slate_lineup_path = "../data/slate_lineups.csv"
    if os.path.exists(slate_lineup_path):
        lineup_files.append(slate_lineup_path)

    if not lineup_files:
        print("❌ No enhanced or slate lineups found! Run optimizer or provide slate_lineups.csv.")
        return []

    lineups = []
    for file in lineup_files:
        filename = os.path.basename(file)
        if filename.startswith("enhanced_lineup_"):
            parts = filename.replace('.csv', '').split('_')
            strategy = parts[2]  # gpp, balanced, cash
            number = parts[3]    # 1, 2, 3
        elif filename == "slate_lineups.csv":
            strategy = "slate"
            number = "1"
        else:
            strategy = "unknown"
            number = "1"

        df = pd.read_csv(file)
        lineups.append({
            'strategy': strategy,
            'number': number,
            'filename': filename,
            'lineup': df,
            'total_salary': df['Salary'].sum(),
            'total_fppg': df['Projected_FPPG'].sum()
        })

    return lineups

def convert_to_fanduel_positions(lineup_df, valid_ids=None):
    """Convert lineup to FanDuel position format"""
    
    # Use provided valid_ids to avoid repeated calls
    if valid_ids is None:
        valid_ids = get_valid_player_ids()
    
    filtered_df = lineup_df[lineup_df['Id'].astype(str).isin(valid_ids)].copy()
    if len(filtered_df) < 9:
        print(f"⚠️ Lineup has only {len(filtered_df)} eligible players after filtering out unavailable players.")

    # Assign players to FanDuel positions, always filling 9 unique slots
    positions = {
        'P': None,
        'C/1B': None,
        '2B': None,
        '3B': None,
        'SS': None,
        'OF': [],
        'UTIL': None
    }
    used_ids = set()

    # Assign pitcher
    p_row = filtered_df[filtered_df['Position'] == 'P']
    if not p_row.empty:
        positions['P'] = p_row.iloc[0]['Id']
        used_ids.add(positions['P'])

    # Assign C/1B (FanDuel allows either C or 1B)
    c_row = filtered_df[filtered_df['Position'] == 'C']
    ib_row = filtered_df[filtered_df['Position'] == '1B']
    if not c_row.empty:
        positions['C/1B'] = c_row.iloc[0]['Id']
        used_ids.add(positions['C/1B'])
    elif not ib_row.empty:
        positions['C/1B'] = ib_row.iloc[0]['Id']
        used_ids.add(positions['C/1B'])

    # Assign 2B, 3B, SS
    for pos in ['2B', '3B', 'SS']:
        row = filtered_df[filtered_df['Position'] == pos]
        if not row.empty:
            positions[pos] = row.iloc[0]['Id']
            used_ids.add(positions[pos])

    # Assign OF (up to 3)
    of_rows = filtered_df[filtered_df['Position'] == 'OF']
    for i in range(min(3, len(of_rows))):
        of_id = of_rows.iloc[i]['Id']
        positions['OF'].append(of_id)
        used_ids.add(of_id)

    # Assign UTIL (must be a player not already used)
    all_ids = set(filtered_df['Id'])
    util_candidates = list(all_ids - used_ids)
    if util_candidates:
        positions['UTIL'] = util_candidates[0]
        used_ids.add(positions['UTIL'])
    else:
        # If all players are used, but we have <9, try to fill with an extra OF
        if len(positions['OF']) < 3 and len(of_rows) > len(positions['OF']):
            for i in range(len(positions['OF']), len(of_rows)):
                of_id = of_rows.iloc[i]['Id']
                if of_id not in used_ids:
                    positions['OF'].append(of_id)
                    used_ids.add(of_id)
                    if len(positions['OF']) == 3:
                        break
        # If still missing, leave UTIL as None (should not happen if input is correct)

    # Defensive: If we have more than 3 OF, move extras to UTIL
    if len(positions['OF']) > 3:
        if positions['UTIL'] is None:
            positions['UTIL'] = positions['OF'].pop()

    # Return in FanDuel order
    return {
        'P': positions['P'],
        'C/1B': positions['C/1B'],
        '2B': positions['2B'],
        '3B': positions['3B'],
        'SS': positions['SS'],
        'OF1': positions['OF'][0] if len(positions['OF']) > 0 else None,
        'OF2': positions['OF'][1] if len(positions['OF']) > 1 else None,
        'OF3': positions['OF'][2] if len(positions['OF']) > 2 else None,
        'UTIL': positions['UTIL']
    }

def populate_fanduel_template(lineups):
    """Populate the actual FanDuel submission CSV template"""
    
    template_path = "../fd_current_slate/Lineups.csv"
    
    if not os.path.exists(template_path):
        print(f"❌ FanDuel template not found: {template_path}")
        return
    
    # Read the template
    template_df = pd.read_csv(template_path)
    print(f"✅ Loaded FanDuel template with {len(template_df)} entries")
    
    # Get the contest entries (first few rows)
    contest_rows = template_df[template_df['entry_id'].notna()].head(len(lineups))
    
    if len(contest_rows) < len(lineups):
        print(f"⚠️ Only {len(contest_rows)} contest entries available for {len(lineups)} lineups")
    
    # Get valid IDs once to avoid repeated calls
    valid_ids = get_valid_player_ids()
    
    # Populate each contest entry with a lineup
    for i, lineup_data in enumerate(lineups[:len(contest_rows)]):
        lineup = lineup_data['lineup']
        strategy = lineup_data['strategy'].upper()
        number = lineup_data['number']
        fppg = lineup_data['total_fppg']
        
        # Convert to FanDuel format
        fd_positions = convert_to_fanduel_positions(lineup, valid_ids)
        
        # Update the template row
        row_idx = contest_rows.index[i]
        template_df.loc[row_idx, 'P'] = fd_positions['P']
        template_df.loc[row_idx, 'C/1B'] = fd_positions['C/1B']
        template_df.loc[row_idx, '2B'] = fd_positions['2B']
        template_df.loc[row_idx, '3B'] = fd_positions['3B']
        template_df.loc[row_idx, 'SS'] = fd_positions['SS']
        template_df.loc[row_idx, 'OF'] = fd_positions['OF1']
        template_df.loc[row_idx, 'OF.1'] = fd_positions['OF2']  # Second OF column
        template_df.loc[row_idx, 'OF.2'] = fd_positions['OF3']  # Third OF column
        template_df.loc[row_idx, 'UTIL'] = fd_positions['UTIL']
        
        # Add description
        description = f"{strategy} Lineup {number} - {fppg:.1f} FPPG"
        template_df.loc[row_idx, 'Instructions'] = description
        
        print(f"✅ Populated {description}")
    
    # Save the updated template
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    output_path = f"../fd_current_slate/Lineups_Ready_To_Submit_{timestamp}.csv"
    template_df.to_csv(output_path, index=False)
    
    print(f"\n🎉 FANDUEL SUBMISSION READY!")
    print(f"📤 Upload this file to FanDuel: {output_path}")
    print(f"✅ Successfully populated {len(lineups)} lineups with FanDuel player IDs")

def create_submission_summary(lineups):
    """Create a readable summary of all lineups"""
    
    summary_data = []
    
    for lineup_data in lineups:
        lineup = lineup_data['lineup']
        strategy = lineup_data['strategy'].upper()
        number = lineup_data['number']

        # Get players by position (from the 9-player DataFrame)
        positions = {}
        for _, player in lineup.iterrows():
            pos = player['Position']
            if pos not in positions:
                positions[pos] = []
            positions[pos].append({
                'name': player['Nickname'],
                'team': player['Team'],
                'salary': player['Salary'],
                'fppg': player['FPPG']  # Changed from Projected_FPPG to FPPG
            })

        summary_data.append({
            'Lineup': f"{strategy} {number}",
            'Total_Salary': lineup['Salary'].sum(),
            'Total_FPPG': lineup['FPPG'].sum(),  # Changed from Projected_FPPG to FPPG
            'Avg_Value': (lineup['FPPG'] / lineup['Salary'] * 1000).mean(),  # Changed from Projected_FPPG to FPPG
            'P': positions.get('P', [{}])[0].get('name', 'N/A'),
            'C': positions.get('C', [{}])[0].get('name', 'N/A'),
            '1B': positions.get('1B', [{}])[0].get('name', 'N/A'),
            '2B': positions.get('2B', [{}])[0].get('name', 'N/A'),
            '3B': positions.get('3B', [{}])[0].get('name', 'N/A'),
            'SS': positions.get('SS', [{}])[0].get('name', 'N/A'),
            'OF1': positions.get('OF', [{}])[0].get('name', 'N/A'),
            'OF2': positions.get('OF', [{}])[1].get('name', 'N/A') if len(positions.get('OF', [])) > 1 else 'N/A',
            'OF3': positions.get('OF', [{}])[2].get('name', 'N/A') if len(positions.get('OF', [])) > 2 else 'N/A',
        })
    
    summary_df = pd.DataFrame(summary_data)
    summary_df.to_csv("../data/fanduel_submission_summary.csv", index=False)
    
    print("\n📋 FANDUEL SUBMISSION SUMMARY:")
    print("=" * 80)
    for _, row in summary_df.iterrows():
        print(f"{row['Lineup']:<15} | ${row['Total_Salary']:>5} | {row['Total_FPPG']:>5.1f} FPPG | {row['Avg_Value']:>4.1f} value")
    
    print(f"\n✅ Detailed summary saved: ../data/fanduel_submission_summary.csv")

def main():
    print("🚀 ENHANCED FANDUEL SUBMISSION CREATOR")
    print("=" * 50)
    
    # Load enhanced lineups
    lineups = load_enhanced_lineups()
    
    if not lineups:
        return
    
    print(f"✅ Found {len(lineups)} enhanced lineups")
    
    # Sort by strategy and number
    lineups.sort(key=lambda x: (x['strategy'], int(x['number'])))
    
    # Show lineup overview
    print("\n📊 LINEUP OVERVIEW:")
    for lineup_data in lineups:
        strategy = lineup_data['strategy'].upper()
        number = lineup_data['number']
        salary = lineup_data['total_salary']
        fppg = lineup_data['total_fppg']
        print(f"  {strategy} {number}: ${salary:,} | {fppg:.1f} FPPG")
    

    # Filter lineups and auto-fill with eligible players if needed
    valid_lineups = []
    valid_ids = get_valid_player_ids()
    # Load eligible player info for filling
    slate_path = '../fd_current_slate/fd_slate_today.csv'
    slate_df = pd.read_csv(slate_path)
    eligible_players = slate_df[slate_df['Id'].astype(str).isin(valid_ids)]


    required_positions = ['P', 'C', '1B', '2B', '3B', 'SS']
    for lineup_data in lineups:
        lineup = lineup_data['lineup']
        eligible_lineup = lineup[lineup['Id'].astype(str).isin(valid_ids)].copy()
        used_ids = list(eligible_lineup['Id'].astype(str))
        # If less than 9, fill with unused eligible players (prioritize by value, not just FPPG)
        if len(eligible_lineup) < 9:
            needed = 9 - len(eligible_lineup)
            fill_candidates = eligible_players[~eligible_players['Id'].astype(str).isin(used_ids)].copy()
            if len(fill_candidates) >= needed:
                # Sort by value (FPPG per $1000 salary) to get best value players
                fill_candidates['Value'] = (fill_candidates['FPPG'] / fill_candidates['Salary']) * 1000
                fill_rows = fill_candidates.sort_values('Value', ascending=False).head(needed)
                fill_rows = fill_rows.reindex(columns=eligible_lineup.columns, fill_value=None)
                eligible_lineup = pd.concat([eligible_lineup, fill_rows], ignore_index=True)
                print(f"⚠️ Filled lineup {lineup_data['strategy'].upper()} {lineup_data['number']} with {needed} value-based players.")
            else:
                print(f"❌ Cannot fill lineup {lineup_data['strategy'].upper()} {lineup_data['number']} (only {len(eligible_lineup)} eligible, {needed} needed, {len(fill_candidates)} available to fill)")
                continue
        # Now eligible_lineup has at least 9 players
        # Ensure we have all required positions before finalizing
        positions_needed = {'P': 1, 'C': 1, '1B': 1, '2B': 1, '3B': 1, 'SS': 1, 'OF': 3}
        current_positions = eligible_lineup['Position'].value_counts().to_dict()
        
        missing_positions = []
        for pos, needed in positions_needed.items():
            if current_positions.get(pos, 0) < needed:
                missing_positions.append(pos)
        
        if missing_positions:
            print(f"⚠️ Lineup {lineup_data['strategy'].upper()} {lineup_data['number']} missing positions: {missing_positions}")
            # Try to fill missing positions from eligible players
            for pos in missing_positions:
                pos_players = eligible_players[eligible_players['Position'] == pos]
                if not pos_players.empty:
                    # Get best value player for this position that's not already used
                    unused_pos_players = pos_players[~pos_players['Id'].astype(str).isin(used_ids)]
                    if not unused_pos_players.empty:
                        unused_pos_players = unused_pos_players.copy()
                        unused_pos_players['Value'] = (unused_pos_players['FPPG'] / unused_pos_players['Salary']) * 1000
                        best_player = unused_pos_players.sort_values('Value', ascending=False).iloc[0]
                        best_player_df = best_player.to_frame().T.reindex(columns=eligible_lineup.columns, fill_value=None)
                        eligible_lineup = pd.concat([eligible_lineup, best_player_df], ignore_index=True)
                        used_ids.append(str(best_player['Id']))
                        print(f"   Added {best_player['Nickname']} ({pos}) to fill missing position")
        
        # Truncate to exactly 9 players
        eligible_lineup = eligible_lineup.head(9)
        
        new_lineup_data = dict(lineup_data)
        new_lineup_data['lineup'] = eligible_lineup
        valid_lineups.append(new_lineup_data)

    if not valid_lineups:
        print("❌ No valid lineups with 9 eligible players found!")
        return

    # Populate FanDuel template
    populate_fanduel_template(valid_lineups)

    # Create summary
    create_submission_summary(valid_lineups)

    print(f"\n🎉 FanDuel submission ready!")
    print(f"   📁 Main file: ../fd_current_slate/Lineups.csv")
    print(f"   📊 Summary: ../data/fanduel_submission_summary.csv")

if __name__ == "__main__":
    main()
