#!/usr/bin/env python3
"""
ENHANCED STACK RANKING SYSTEM - COMPLETE METHODOLOGY
Now includes weather/park factors and opposing pitcher analysis
"""

print("🎯 ENHANCED STACK RANKING SYSTEM - COMPLETE BREAKDOWN")
print("="*70)

print("\n📊 1. CORE DATA SOURCES:")
print("   • Player Projections: Individual fantasy point projections")
print("   • Salary Data: Cost constraints for value calculation")
print("   • Team Assignment: Stack grouping by team")
print("   • Position Filter: Hitters only (no pitchers in hitting stacks)")
print("   • Weather Data: Temperature, wind, humidity, conditions")
print("   • Pitcher Data: Opposing pitcher stats and quality metrics")
print("   • Park Factors: Ballpark offensive/defensive characteristics")

print("\n🔥 2. MULTI-LAYERED MULTIPLIER SYSTEM:")

print("\n   LAYER 1: HISTORICAL PERFORMANCE (Backtest-Based)")
print("   🔥 EXPLOSIVE TEAMS (1.35x-1.45x):")
print("   • PHI, SD, NYY: 1.45x (biggest historical surprises)")
print("   • ATH, COL, KC, TEX: 1.35x (consistent over-performers)")
print("   • Logic: These teams scored 113-140 actual vs 46-47 projected")
print()
print("   📉 CONSERVATIVE TEAMS (0.95x):")
print("   • CIN, ATL, CWS, SF: 0.95x (we consistently over-project)")
print("   • Logic: We over-projected these by 161-310% in backtest")
print()
print("   ⚖️ STANDARD TEAMS (1.20x):")
print("   • All others: 1.20x (accounts for 23% conservative bias)")

print("\n   LAYER 2: WEATHER CONDITIONS (0.8x-1.3x)")
print("   🌤️ TEMPERATURE FACTORS:")
print("   • 70-85°F: +5% (ideal hitting weather)")
print("   • >90°F: +2% (hot weather, ball carries)")
print("   • <60°F: -3% (cold weather hurts offense)")
print()
print("   💨 WIND FACTORS:")
print("   • Wind blowing out (90-270°, >10mph): +8%")
print("   • Wind blowing in (<90° or >270°, >15mph): -5%")
print()
print("   💧 HUMIDITY & CONDITIONS:")
print("   • Low humidity (<40%): +3% (ball carries better)")
print("   • High humidity (>80%): -2% (heavier air)")
print("   • Clear/Sunny: +2%")
print("   • Rain/Storms: -10% (significantly hurts offense)")

print("\n   LAYER 3: OPPOSING PITCHER QUALITY (0.7x-1.4x)")
print("   ⚾ PITCHER QUALITY METRICS:")
print("   • Strikeout Rate:")
print("     - High K/IP (>1.2): -8% (tough to hit)")
print("     - Low K/IP (<0.7): +10% (hittable)")
print()
print("   • Walk Rate:")
print("     - High BB/IP (>0.5): +8% (wild, creates opportunities)")
print("     - Low BB/IP (<0.2): -5% (precise control)")
print()
print("   • Home Run Rate:")
print("     - High HR/IP (>0.15): +12% (homer prone)")
print("     - Low HR/IP (<0.05): -6% (keeps ball in yard)")
print()
print("   • WHIP (Walks + Hits per Inning):")
print("     - High WHIP (>1.5): +15% (poor pitcher)")
print("     - Low WHIP (<1.0): -12% (excellent pitcher)")

print("\n   LAYER 4: BALLPARK FACTORS (0.85x-1.25x)")
print("   🏟️ PARK CHARACTERISTICS:")
print("   • Runs Factor: Primary offensive multiplier")
print("     - Coors Field (COL): 1.154x (extreme hitter park)")
print("     - Wrigley Field (CHC): 1.083x (hitter friendly)")
print("     - Petco Park (SD): 0.924x (pitcher friendly)")
print()
print("   • Home Run Factor (30% weight):")
print("     - Yankee Stadium: HR-friendly right field")
print("     - Fenway Park: Green Monster effects")
print()
print("   • Altitude Effects:")
print("     - High altitude (>3000 ft): +8% (ball carries)")
print("     - Coors Field: Thinner air, more offense")
print()
print("   • Foul Territory:")
print("     - Small foul territory: +3% (more fair balls)")
print("     - Large foul territory: -3% (more foul outs)")
print()
print("   • Wind Impact:")
print("     - Parks with prevailing winds out: +5%")
print("     - Parks with prevailing winds in: -4%")

print("\n💰 3. ENHANCED VALUE CALCULATION:")
print("   Formula: enhanced_projection / (total_salary / 1000)")
print("   Where enhanced_projection = base × historical × weather × pitcher")
print("   Example: 45 base × 1.45 historical × 1.1 weather × 1.2 pitcher = 86.1 pts")

print("\n👥 4. DYNAMIC OWNERSHIP PROJECTIONS:")
print("   Base Ownership:")
print("   • Explosive teams: 12% + rank modifier")
print("   • Standard teams: 7% + rank modifier")
print()
print("   Weather Boost: (weather_multiplier - 1) × 5%")
print("   • Good weather games get higher ownership")
print()
print("   Pitcher Boost: (pitcher_multiplier - 1) × 3%")
print("   • Weak pitching matchups get higher ownership")

print("\n🏆 5. VISUAL STACK CLASSIFICATION:")
print("   Base Team Type + Contextual Factors")
print("   Examples:")
print("   • '🔥 Explosive + 🌤️ Weather + ⚾ Weak Pitching'")
print("   • '⚖️ Standard + 🌤️ Weather'")
print("   • '📉 Conservative + ⚾ Weak Pitching'")

print("\n📈 6. FINAL RANKING ALGORITHM:")
print("   1. Calculate base projection (top 4 hitters)")
print("   2. Apply historical performance multiplier")
print("   3. Apply weather condition multiplier")
print("   4. Apply opposing pitcher quality multiplier")
print("   5. Calculate enhanced value score")
print("   6. Determine dynamic ownership projection")
print("   7. Classify with visual indicators")
print("   8. Sort by total enhanced projection")

print("\n🎲 7. STRATEGIC INTERPRETATION:")

print("\n   🔥 EXPLOSIVE + 🌤️ + ⚾ (Triple Enhanced):")
print("   • Tournament GPP plays (massive ceiling)")
print("   • Accept higher ownership for proven upside")
print("   • Example: PHI with good weather vs weak pitcher")

print("\n   ⚖️ STANDARD + Weather/Pitcher:")
print("   • Balanced plays with situational edge")
print("   • Good for cash games and smaller GPPs")

print("\n   📉 CONSERVATIVE (Even Enhanced):")
print("   • Fade unless extremely low owned")
print("   • Weather/pitcher factors may not overcome base issues")

print("\n🔍 8. REAL-WORLD IMPACT EXAMPLES:")
print("   Scenario 1: PHI vs Bad Pitcher in 85°F, Wind Blowing Out")
print("   • Base: 45 pts")
print("   • Historical: 45 × 1.45 = 65.3")
print("   • Weather: 65.3 × 1.13 = 73.8")
print("   • Pitcher: 73.8 × 1.25 = 92.3 FINAL")
print("   • Classification: '🔥 Explosive + 🌤️ Weather + ⚾ Weak Pitching'")
print()
print("   Scenario 2: CIN vs Ace Pitcher in Cold, Windy Conditions")
print("   • Base: 45 pts")
print("   • Historical: 45 × 0.95 = 42.8")
print("   • Weather: 42.8 × 0.85 = 36.4")
print("   • Pitcher: 36.4 × 0.75 = 27.3 FINAL")
print("   • Classification: '📉 Conservative' (no enhancements shown)")

print("\n✅ SUMMARY - ENHANCED 'BEST' STACK CRITERIA:")
print("   1. High individual player projections (talent)")
print("   2. Positive historical performance pattern")
print("   3. Favorable weather conditions")
print("   4. Weak opposing pitcher matchup")
print("   5. Salary efficiency (enhanced value)")
print("   6. Strategic ownership considerations")
print("   7. Clear visual classification for quick decisions")

print("\nThe enhanced system now accounts for ALL major factors affecting")
print("offensive performance: talent, history, weather, and matchups!")
