#!/usr/bin/env python3
"""
VALIDATE ENHANCED TOURNAMENT SYSTEM
Test the new enhanced system against August 13th actual results
"""

import pandas as pd
import numpy as np

def validate_enhanced_system():
    """Validate the enhanced tournament system lineups against actual results"""
    
    print(" ENHANCED SYSTEM VALIDATION")
    print("=" * 50)
    print("Testing enhanced tournament system against August 13th actual results...")
    
    try:
        # Load actual results
        df_results = pd.read_csv("../data/actual_results_20250813.csv")
        print(f"SUCCESS: Loaded actual results: {len(df_results)} players")
        
        # Load enhanced projections
        df_projections = pd.read_csv("../data/enhanced_projections_20250813_175916.csv")
        print(f"SUCCESS: Loaded projections: {len(df_projections)} players")
        
        # Merge data for validation
        df_merged = merge_results_with_projections(df_results, df_projections)
        
        # Simulate the lineups we just generated
        lineups = simulate_enhanced_lineups(df_merged)
        
        # Validate each lineup
        print(f"\nDATA: LINEUP VALIDATION RESULTS:")
        print("=" * 40)
        
        for lineup_name, lineup_data in lineups.items():
            actual_score = calculate_actual_score(lineup_data, df_merged)
            projected_score = sum(player.get('aggressive_projection', player.get('FPPG', 0)) for player in lineup_data)
            
            print(f"\nTARGET: {lineup_name}:")
            print(f"   PROGRESS: Projected: {projected_score:.1f} points")
            print(f"   LINEUP: Actual: {actual_score:.1f} points")
            print(f"   DATA: Accuracy: {(actual_score/projected_score*100):.1f}%")
            
            # Show key players
            top_performers = sorted(lineup_data, key=lambda x: get_actual_points(x, df_merged), reverse=True)[:3]
            print(f"    Top performers:")
            for player in top_performers:
                actual_pts = get_actual_points(player, df_merged)
                proj_pts = player.get('aggressive_projection', player.get('FPPG', 0))
                print(f"      {player['Nickname']} {player['Last Name']} ({player['Team']}): {actual_pts:.1f} pts (proj: {proj_pts:.1f})")
        
        # Compare to known good performers
        print(f"\n COMPARISON TO KNOWN WINNERS:")
        print("=" * 35)
        print(f"   Winner threshold: ~271 points")
        print(f"   Cash threshold: ~200 points")
        
        best_lineup = max(lineups.items(), key=lambda x: calculate_actual_score(x[1], df_merged))
        best_score = calculate_actual_score(best_lineup[1], df_merged)
        
        print(f"\nLINEUP: BEST ENHANCED LINEUP: {best_lineup[0]}")
        print(f"   Actual score: {best_score:.1f} points")
        
        if best_score >= 271:
            print(f"    WOULD HAVE WON THE TOURNAMENT!")
        elif best_score >= 200:
            print(f"   MONEY: WOULD HAVE CASHED!")
        else:
            print(f"   ERROR: Would not have cashed")
            
        # Show winning percentage of our system
        cash_count = sum(1 for lineup_data in lineups.values() 
                        if calculate_actual_score(lineup_data, df_merged) >= 200)
        
        print(f"\nPROGRESS: SYSTEM PERFORMANCE:")
        print(f"   MONEY: {cash_count}/{len(lineups)} lineups would have cashed ({cash_count/len(lineups)*100:.1f}%)")
        
        return lineups, df_merged
        
    except Exception as e:
        print(f"ERROR: Error: {e}")
        import traceback
        traceback.print_exc()

def merge_results_with_projections(df_results, df_projections):
    """Merge actual results with projections for validation"""
    
    # Create name matching columns (actual results has 'name', projections has separate first/last)
    df_projections['full_name'] = df_projections['Nickname'] + ' ' + df_projections['Last Name']
    
    # Merge on full name and team
    df_merged = df_projections.merge(
        df_results[['name', 'team', 'fanduel_points']], 
        left_on=['full_name', 'Team'], 
        right_on=['name', 'team'], 
        how='left'
    )
    
    print(f"   Matched {len(df_merged[df_merged['fanduel_points'].notna()])} players with actual results")
    
    return df_merged

def simulate_enhanced_lineups(df_merged):
    """Simulate the lineups that would have been generated by our enhanced system"""
    
    # These represent the strategies our enhanced system would have chosen
    lineups = {
        "Top Game Stack (CHC@TOR)": get_top_game_stack_lineup(df_merged, "CHC@TOR"),
        "HOU Team Stack": get_team_stack_lineup(df_merged, "HOU"),
        "CLE Contrarian Stack": get_team_stack_lineup(df_merged, "CLE"),
        "MIA Value Stack": get_team_stack_lineup(df_merged, "MIA"),
        "Hybrid TOR/HOU": get_hybrid_lineup(df_merged, "TOR", "HOU")
    }
    
    return lineups

def get_top_game_stack_lineup(df_merged, game):
    """Get players that would have been selected for game stack"""
    
    # Extract teams from game
    teams = game.split('@')
    
    # Get players from both teams
    game_players = df_merged[df_merged['Team'].isin(teams)]
    
    # Select best pitcher from game
    pitchers = game_players[(game_players['Position'] == 'P') & (game_players['Probable Pitcher'] == 'Yes')]
    if len(pitchers) == 0:
        return []
    
    lineup = []
    used_players = set()
    remaining_salary = 35000
    
    # Add best pitcher
    pitcher = pitchers.sort_values('FPPG', ascending=False).iloc[0]
    lineup.append(pitcher.to_dict())
    used_players.add(pitcher['Id'])
    remaining_salary -= pitcher['Salary']
    
    # Add hitters from game
    hitters = game_players[
        (game_players['Position'] != 'P') & 
        (game_players['Batting Order'] > 0) &
        (~game_players['Id'].isin(used_players))
    ].sort_values('FPPG', ascending=False)
    
    positions_needed = ['C', '1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF']
    
    for pos in positions_needed:
        eligible = hitters[
            (hitters['Position'].str.contains(pos, na=False) if pos != 'OF' else hitters['Position'] == 'OF') &
            (hitters['Salary'] <= remaining_salary)
        ]
        
        if len(eligible) > 0:
            player = eligible.iloc[0]
            lineup.append(player.to_dict())
            used_players.add(player['Id'])
            remaining_salary -= player['Salary']
            hitters = hitters[~hitters['Id'].isin(used_players)]
    
    return lineup

def get_team_stack_lineup(df_merged, team):
    """Get players that would have been selected for team stack"""
    
    lineup = []
    used_players = set()
    remaining_salary = 35000
    
    # Get non-team pitcher (value pitcher)
    pitchers = df_merged[
        (df_merged['Position'] == 'P') & 
        (df_merged['Probable Pitcher'] == 'Yes') &
        (df_merged['Team'] != team) &
        (df_merged['Salary'] >= 6000) &
        (df_merged['Salary'] <= 10000)
    ].sort_values('FPPG', ascending=False)
    
    if len(pitchers) > 0:
        pitcher = pitchers.iloc[0]
        lineup.append(pitcher.to_dict())
        used_players.add(pitcher['Id'])
        remaining_salary -= pitcher['Salary']
    
    # Get team players
    team_players = df_merged[
        (df_merged['Team'] == team) &
        (df_merged['Position'] != 'P') &
        (df_merged['Batting Order'] > 0)
    ].sort_values('FPPG', ascending=False)
    
    positions_needed = ['C', '1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF']
    
    for pos in positions_needed:
        # Try team players first
        eligible_team = team_players[
            (team_players['Position'].str.contains(pos, na=False) if pos != 'OF' else team_players['Position'] == 'OF') &
            (team_players['Salary'] <= remaining_salary) &
            (~team_players['Id'].isin(used_players))
        ]
        
        if len(eligible_team) > 0:
            player = eligible_team.iloc[0]
        else:
            # Fall back to any team
            all_eligible = df_merged[
                (df_merged['Position'].str.contains(pos, na=False) if pos != 'OF' else df_merged['Position'] == 'OF') &
                (df_merged['Position'] != 'P') &
                (df_merged['Salary'] <= remaining_salary) &
                (~df_merged['Id'].isin(used_players))
            ].sort_values('FPPG', ascending=False)
            
            if len(all_eligible) > 0:
                player = all_eligible.iloc[0]
            else:
                continue
        
        lineup.append(player.to_dict())
        used_players.add(player['Id'])
        remaining_salary -= player['Salary']
    
    return lineup

def get_hybrid_lineup(df_merged, team1, team2):
    """Get hybrid lineup mixing two teams"""
    
    lineup = []
    used_players = set()
    remaining_salary = 35000
    
    # Get pitcher from non-primary team
    pitchers = df_merged[
        (df_merged['Position'] == 'P') & 
        (df_merged['Probable Pitcher'] == 'Yes') &
        (~df_merged['Team'].isin([team1, team2])) &
        (df_merged['Salary'] >= 6000) &
        (df_merged['Salary'] <= 10000)
    ].sort_values('FPPG', ascending=False)
    
    if len(pitchers) > 0:
        pitcher = pitchers.iloc[0]
        lineup.append(pitcher.to_dict())
        used_players.add(pitcher['Id'])
        remaining_salary -= pitcher['Salary']
    
    # Get players from both teams
    target_players = df_merged[
        (df_merged['Team'].isin([team1, team2])) &
        (df_merged['Position'] != 'P') &
        (df_merged['Batting Order'] > 0)
    ].sort_values('FPPG', ascending=False)
    
    positions_needed = ['C', '1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF']
    
    for pos in positions_needed:
        eligible = target_players[
            (target_players['Position'].str.contains(pos, na=False) if pos != 'OF' else target_players['Position'] == 'OF') &
            (target_players['Salary'] <= remaining_salary) &
            (~target_players['Id'].isin(used_players))
        ]
        
        if len(eligible) > 0:
            player = eligible.iloc[0]
            lineup.append(player.to_dict())
            used_players.add(player['Id'])
            remaining_salary -= player['Salary']
    
    return lineup

def calculate_actual_score(lineup, df_merged):
    """Calculate actual score for a lineup"""
    
    total_score = 0
    for player in lineup:
        actual_pts = get_actual_points(player, df_merged)
        total_score += actual_pts
    
    return total_score

def get_actual_points(player, df_merged):
    """Get actual points for a player"""
    
    player_id = player.get('Id')
    if player_id:
        match = df_merged[df_merged['Id'] == player_id]
        if len(match) > 0 and not pd.isna(match.iloc[0]['fanduel_points']):
            return match.iloc[0]['fanduel_points']
    
    # Fall back to 0 if no match
    return 0.0

if __name__ == "__main__":
    validate_enhanced_system()
