import pandas as pd
df = pd.read_csv('C:/Users/kgone/OneDrive/Personal_Information/MLB/data/finalize_hitter_features.csv')
print(df[['rolling_avg_hits', 'rolling_avg_OBP']].describe())
print("Non-default rolling_avg_hits:", len(df[df['rolling_avg_hits'] != 0.229]))
print("Non-default rolling_avg_OBP:", len(df[df['rolling_avg_OBP'] != 0.298]))
print("Rows with league average AVG (0.229):", len(df[df['rolling_avg_hits'] == 0.229]))
print("Rows with league average OBP (0.298):", len(df[df['rolling_avg_OBP'] == 0.298]))
print("Zero-value rows:")
print(df[df['rolling_avg_hits'] == 0][['player_id', 'rolling_avg_hits', 'rolling_avg_OBP']])
print("Stats for previously zero-value rows:")
print(df[df['player_id'].isin(['118689-119439', '118689-82661'])][['player_id', 'rolling_avg_hits', 'rolling_avg_OBP', 'low_pa_flag']])
print("Kyle Schwarber row:")
print(df[df['player_id'] == '118689-60631'][['player_id', 'rolling_avg_hits', 'rolling_avg_OBP', 'low_pa_flag']])
print("Bryce Harper row:")
print(df[df['player_id'] == '118689-12948'][['player_id', 'rolling_avg_hits', 'rolling_avg_OBP', 'low_pa_flag']])
print("Players with low_pa_flag == True:")
print(df[df['low_pa_flag'] == True][['player_id', 'rolling_avg_hits', 'rolling_avg_OBP', 'low_pa_flag']])